/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VEC_H_RPCGEN
#define _VEC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct parameters {
	int vector[100];
	int function;
	int functionParameter;
};
typedef struct parameters parameters;

struct resultVector {
	int rVector[100];
};
typedef struct resultVector resultVector;

#define VEC_PROG 0x23451111
#define VEC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define powVector 1
extern  resultVector * powvector_1(parameters *, CLIENT *);
extern  resultVector * powvector_1_svc(parameters *, struct svc_req *);
#define logVector 2
extern  resultVector * logvector_1(parameters *, CLIENT *);
extern  resultVector * logvector_1_svc(parameters *, struct svc_req *);
#define multiplyVector 3
extern  resultVector * multiplyvector_1(parameters *, CLIENT *);
extern  resultVector * multiplyvector_1_svc(parameters *, struct svc_req *);
#define sumVector 4
extern  int * sumvector_1(parameters *, CLIENT *);
extern  int * sumvector_1_svc(parameters *, struct svc_req *);
#define normVector 5
extern  int * normvector_1(parameters *, CLIENT *);
extern  int * normvector_1_svc(parameters *, struct svc_req *);
#define edgeVector 6
extern  int * edgevector_1(parameters *, CLIENT *);
extern  int * edgevector_1_svc(parameters *, struct svc_req *);
extern int vec_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define powVector 1
extern  resultVector * powvector_1();
extern  resultVector * powvector_1_svc();
#define logVector 2
extern  resultVector * logvector_1();
extern  resultVector * logvector_1_svc();
#define multiplyVector 3
extern  resultVector * multiplyvector_1();
extern  resultVector * multiplyvector_1_svc();
#define sumVector 4
extern  int * sumvector_1();
extern  int * sumvector_1_svc();
#define normVector 5
extern  int * normvector_1();
extern  int * normvector_1_svc();
#define edgeVector 6
extern  int * edgevector_1();
extern  int * edgevector_1_svc();
extern int vec_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_parameters (XDR *, parameters*);
extern  bool_t xdr_resultVector (XDR *, resultVector*);

#else /* K&R C */
extern bool_t xdr_parameters ();
extern bool_t xdr_resultVector ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VEC_H_RPCGEN */
