/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vec.h"
#include <time.h>
#include <stdlib.h>

void
callServer(char *host,int vector[])
{
	CLIENT *clnt;
	resultVector  *result_1;
	parameters  powvector_1_arg;
	resultVector  *result_2;
	parameters  logvector_1_arg;
	resultVector  *result_3;
	parameters  multiplyvector_1_arg;
	int  *result_4;
	parameters  sumvector_1_arg;
	int  *result_5;
	parameters  normvector_1_arg;
	int  *result_6;
	parameters  edgevector_1_arg;

	parameters  parameters;

#ifndef	DEBUG
	clnt = clnt_create (host, VEC_PROG, VEC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	edgevector_1_arg.function = 161095;
	int i;
	for(i =0; i < 100;i++){
		parameters.vector[i] = vector[i];
	}


	result_1 = powvector_1(&powvector_1_arg, clnt);
	if (result_1 == (resultVector *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = logvector_1(&logvector_1_arg, clnt);
	if (result_2 == (resultVector *) NULL) {
		clnt_perror (clnt, "call failed");
	}


	result_3 = multiplyvector_1(&parameters, clnt);
	if (result_3 == (resultVector *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("TesteS %i\n ", result_3->rVector[1]);
	 }

	result_4 = sumvector_1(&sumvector_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = normvector_1(&normvector_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = edgevector_1(&edgevector_1_arg, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	// else{
	// 	printf("TesteS %i\n ", *result_6);
	// }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc > 5 ) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int numberOfelements = 100;
	srand(time(NULL));
	int vector[numberOfelements];
	int i;
	for(i =0; i < numberOfelements;i++){
		vector[i] = rand() % 10;
	}
	printf("testeC %d",vector[1]);
	callServer (host,vector);
exit (0);
}
