/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "vec.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
vec_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		parameters powvector_1_arg;
		parameters shiftvector_1_arg;
		parameters multiplyvector_1_arg;
		parameters sumvector_1_arg;
		parameters thresholdvector_1_arg;
		parameters edgevector_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case powVector:
		_xdr_argument = (xdrproc_t) xdr_parameters;
		_xdr_result = (xdrproc_t) xdr_resultVector;
		local = (char *(*)(char *, struct svc_req *)) powvector_1_svc;
		break;

	case shiftVector:
		_xdr_argument = (xdrproc_t) xdr_parameters;
		_xdr_result = (xdrproc_t) xdr_resultVector;
		local = (char *(*)(char *, struct svc_req *)) shiftvector_1_svc;
		break;

	case multiplyVector:
		_xdr_argument = (xdrproc_t) xdr_parameters;
		_xdr_result = (xdrproc_t) xdr_resultVector;
		local = (char *(*)(char *, struct svc_req *)) multiplyvector_1_svc;
		break;

	case sumVector:
		_xdr_argument = (xdrproc_t) xdr_parameters;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) sumvector_1_svc;
		break;

	case thresholdVector:
		_xdr_argument = (xdrproc_t) xdr_parameters;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) thresholdvector_1_svc;
		break;

	case edgeVector:
		_xdr_argument = (xdrproc_t) xdr_parameters;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) edgevector_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (VEC_PROG, VEC_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, VEC_PROG, VEC_VERS, vec_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (VEC_PROG, VEC_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, VEC_PROG, VEC_VERS, vec_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (VEC_PROG, VEC_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
