/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vec.h"
#include <time.h>
#include <stdlib.h>

void
callServer(char *host,int vector[],int pickedFunction ,int functionParameter)
{
	CLIENT *clnt;
	resultVector  *resultES;
	int  *resultIN;
	parameters  parameters;

#ifndef	DEBUG
	clnt = clnt_create (host, VEC_PROG, VEC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	parameters.functionParameter = functionParameter;
	int i;
	for(i =0; i < 100;i++){
		parameters.vector[i] = vector[i];
	}

	switch (pickedFunction){
		case 1:
			resultES = powvector_1(&parameters, clnt);
			if (resultES == (resultVector *) NULL) {
			clnt_perror (clnt, "call failed");
			}
			break;
		case 2:
			resultES = shiftvector_1(&parameters, clnt);
			if (resultES == (resultVector *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			break;
		case 3:
			resultES = multiplyvector_1(&parameters, clnt);
			if (resultES == (resultVector *) NULL) {
			clnt_perror (clnt, "call failed");
			}
			break;
		case 4:
		resultIN = sumvector_1(&parameters, clnt);
			if (resultIN == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}		
			break;
		case 5:
			resultIN= thresholdvector_1(&parameters, clnt);
			if (resultIN == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			break;
		case 6:
			resultIN = edgevector_1(&parameters, clnt);
			if (resultIN == (int *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			break;
		}

		if (pickedFunction < 4){	
			for(i =0; i < 100;i++){
				printf(" %i ", resultES->rVector[i]);
			}
				printf("\n");
		}
		else{
			printf(" %i ", *resultIN);
		}


#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc > 5 ) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	int function = atoi(argv[2]);
	int functionParameter = atoi(argv[3]);
	int numberOfelements = 100;
	srand(time(NULL));
	int vector[numberOfelements];
	int i;
	for(i =0; i < numberOfelements;i++){
		vector[i] = rand() % 100;
	}
	callServer (host,vector,function,functionParameter);
exit (0);
}

