/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vec.h"

resultVector *
powvector_1_svc(parameters *argp, struct svc_req *rqstp)
{
	static resultVector  result;

	int i;
	int j;
	int number;
	int mult;
	for(i = 0; i < 100;i++){
		int mult = argp->vector[i];
		int number = argp->vector[i];
		for(j =1; j < argp->functionParameter ; j++){
			number = number * mult;
		}
		result.rVector[i] = number;
	}
	return &result;
}

// Mudar esse metodo para o nome shift

resultVector *
logvector_1_svc(parameters *argp, struct svc_req *rqstp)
{
	static resultVector  result;

	int i;
	for(i =0; i < 100;i++){
		result.rVector[i] = argp->vector[i] + argp->functionParameter;
	}

	return &result;
}

resultVector *
multiplyvector_1_svc(parameters *argp, struct svc_req *rqstp)
{
	static resultVector  result;

	int i;
	for(i =0; i < 100;i++){
		result.rVector[i] = argp->vector[i] * argp->functionParameter;
	}


	return &result;
}

int *
sumvector_1_svc(parameters *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
normvector_1_svc(parameters *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
edgevector_1_svc(parameters *argp, struct svc_req *rqstp)
{
	static int  result;

	result = 1;
	return &result;
}
